apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
  namespace: default
  labels:
    app: busybox
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container
