logging:
  level:
    com.example.sgm: debug
    com.baomidou.mybatisplus.mapper: DEBUG

# DataSource Config
spring:
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:test
#    username: root
#    password: test
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    initialSize: 10
    maxActive: 30
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: ''
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:h2:mem:test
    username: root
    validationQuery: SELECT 1
  #
  #    driver-class-name: org.h2.Driver
  #    username: root
  #    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  web:
    resources:
      static-locations:
        - classpath:/static/

