
logging:
  level:
    com.example.sgm: debug
    com.baomidou.mybatisplus.mapper: DEBUG

# DataSource Config
spring:
  freemarker:
    suffix: .ftl
  #jsp支持
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    #关闭默认模板引擎（thymeleaf）,才会支持jsp
  thymeleaf:
    cache: false
    enabled: true

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test

  #
  #    driver-class-name: org.h2.Driver
  #    username: root
  #    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  web:
    resources:
      static-locations:
        - classpath:/static/
  data:
    redis:
      host: 192.168.56.23
      password:
      port: 6379
      database: 0
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.23:3306/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password:
#    # druid 连接池管理
#    druid:
#      filter:
#        config:
#          #开启密钥加密
#          enabled: true
#        stat:
#          enabled: true
#          log-slow-sql: true
#      # 配置默认的监控统计拦截的Filter
#      # 不配置则监控页面中的SQL无法统计
#      # stat - SQL监控配置
#      # wall - SQL防火墙配置
#      # slf4j - Druid日志配置
#      filters: stat,wall,slf4j
#      # 初始化连接池大小
#      initial-size: 5
#      # 连接池最大连接数
#      max-active: 20
#      # 每个连接上PSCache的最大值
#      # 如果大于0，pool-prepared-statements自动开启
#      max-pool-prepared-statement-per-connection-size: -1
#      # 连接时最大等待时间（单位：毫秒）
#      max-wait: 60000
#      # 保持空闲连接不被关闭的最小生存时间（单位：毫秒）
#      min-evictable-idle-time-millis: 300000
#      # 连接池最小空闲数
#      min-idle: 5
#      # 是否开启PSCache，即是否缓存preparedStatement（提升写入、查询效率）
#      # 建议在支持游标的数据库开启，例如：Oracle
#      pool-prepared-statements: false
#      # 检测获取连接时的有效性
#      # 开启后会影响性能
#      test-on-borrow: false
#      # 检测归还连接时的有效性
#      # 开启后会影响性能
#      test-on-return: false
#      # 检测空闲连接
#      # 不影响性能，建议开启
#      test-while-idle: true
#      # 检测关闭空闲连接的时间间隔（单位：毫秒）
#      time-between-eviction-runs-millis: 60000
#      # 检测连接有效的SQL
#      # 为空则test-while-idle、test-on-borrow、test-on-return配置失效
#      validation-query: SELECT 1
#      # 检测连接是否有效的超时时间
#      validation-query-timeout: 1
#      stat-view-servlet:
#        # 访问白名单
#        allow: 127.0.0.1
#        # 配置统计页面
#        enabled: true
#        # 访问密码
#        login-password: 123456
#        # 访问用户名
#        login-username: root
#        # 允许重置监控数据
#        reset-enable: true
#        # 配置Servlet的访问路径：访问路径为/druid/**时，跳转到StatViewServlet，会自动转到Druid监控后台
#        url-pattern: /druid/*
#      web-stat-filter:
#        # 配置统计页面过滤
#        enabled: true
#        # 排除路径
#        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
#        # 开启session统计
#        session-stat-enable: true
#        # session统计的最大个数
#        session-stat-max-count: 100
#        # 过滤路径
#        url-pattern: /*
